# Generated by Django 6.0.7 on 2026-07-25 18:57

import content.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(storage=content.storage.VideoStorage(), upload_to='videos/'),
        ),
    ]
