# Generated by Django 6.0.7 on 2026-07-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_embeddings_alter_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='embeddings',
            new_name='embedding',
        ),
    ]
