# Generated by Django 6.0.7 on 2026-07-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged')], default='pending', max_length=20),
        ),
    ]
