# Generated by Django 6.0.7 on 2026-07-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('tech', 'TECH'), ('travel', 'TRAVEL'), ('sports', 'SPORTS'), ('lifestyle', 'LIFESTYLE'), ('education', 'EDUCATION'), ('entertainment', 'ENTERTAINMENT'), ('other', 'OTHER')], default='other', max_length=20),
        ),
    ]
